name: Test Workflow

"on":
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/news-update.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test geslaagd
        run: echo "WorldCup Live Pro GitHub Actions werkt!"
